name: deploy_test

on:
  push:
    tags:
      - release-*

env:
  FEAT_NOTES: ${{ secrets.DEV_FEAT_NOTES }}
  BUG_NOTES: ${{ secrets.DEV_BUG_NOTES }}

jobs:
  notify_mattermost:
    runs-on: ubuntu-latest
    steps:
      - name: Create the Mattermost Message
        run: |
          echo $(ls ${GITHUB_WORKSPACE}) && \
          bash ../scripts/mattermost.sh
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: https://chat.executionlab.asia/hooks/rea9tkua7tf1uns7tr3e6jkgha
          MATTERMOST_USERNAME: test_deployment
          MATTERMOST_ICON: https://banhmipate.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/banh-mi-pate-truyenthong.png.webp
