name: deploy_test

on:
  push:
    tags:
      - release-*

env:
  NOTES: ${{ secrets.DEV_NOTES }}

jobs:
  notify_mattermost:
    runs-on: ubuntu-latest
    steps:
      - name: Create the Mattermost Message
        run: |
          echo "{\"text\":\"![](https://img.shields.io/badge/dev-blue?label=environment)  ![](https://img.shields.io/badge/1.1.0-red?label=version)\\n\\nRelease `Frontend` done! :agon-clap: \\nURL: https://order.dev.banhmipate.com\\n\\n#### :noted: Release notes: \\n---\\n:bulb: **New features/Enhancements:**\\n${NOTES}\\n---\\n:ladybug: **Bug fixes:**\\n\\ncc @trang.nguyen @toan.le @vy.huynh @giau.nguyen @hung.huynh @thu.bui @danh.nguyen\\\"}\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: https://chat.executionlab.asia/hooks/rea9tkua7tf1uns7tr3e6jkgha
          MATTERMOST_USERNAME: test_deployment
          MATTERMOST_ICON: https://banhmipate.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/banh-mi-pate-truyenthong.png.webp
