name: deploy_test

on:
  push:
    branch:
      - main

env:
  FEAT_NOTES: ${{ secrets.DEV_FEAT_NOTES }}
  BUG_NOTES: ${{ secrets.DEV_BUG_NOTES }}

jobs:
  setup_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: setup env
        run: | 
          echo $(ls -la /home/runner/work) && \
          echo "APP_VERSION=$(bash .github/scripts/version.sh)" >> $GITHUB_ENV
  
  notify_mattermost:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Create the Mattermost Message
        run: |
          echo $(ls -la /home/runner/work/github-action-test) && \
          bash .github/scripts/mattermost.sh 
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: https://chat.executionlab.asia/hooks/rea9tkua7tf1uns7tr3e6jkgha
          MATTERMOST_USERNAME: test_deployment
          MATTERMOST_ICON: https://banhmipate.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/03/banh-mi-pate-truyenthong.png.webp
